# Generated by Django 5.0.6 on 2024-06-02 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BaseSettings', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название товара')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('allColors', models.ManyToManyField(to='BaseSettings.colorproduct', verbose_name='Цвет')),
                ('allMemory', models.ManyToManyField(to='BaseSettings.memoryproducts', verbose_name='Память')),
                ('images', models.ManyToManyField(to='BaseSettings.imagesproduct', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Аксессуар',
                'verbose_name_plural': 'Аксессуары',
            },
        ),
        migrations.CreateModel(
            name='AccessoriesOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.accessories', verbose_name='Аксессуар')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BaseSettings.colorproduct', verbose_name='Цвет')),
                ('memory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BaseSettings.memoryproducts', verbose_name='Память')),
                ('sim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BaseSettings.simproduct', verbose_name='Тип сим-карты')),
            ],
        ),
        migrations.CreateModel(
            name='Covers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.SlugField(editable=False, max_length=255, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='Название товара')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('color', models.ManyToManyField(to='BaseSettings.colorproduct', verbose_name='Цвет')),
                ('images', models.ManyToManyField(to='BaseSettings.imagesproduct', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Чехол',
                'verbose_name_plural': 'Чехлы',
            },
        ),
        migrations.CreateModel(
            name='IMac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название товара')),
                ('allColors', models.ManyToManyField(related_name='all_device_imac', to='BaseSettings.colorproduct', verbose_name='Цвета iMac')),
                ('allMemory', models.ManyToManyField(related_name='all_memory_imac', to='BaseSettings.memoryproducts', verbose_name='Память')),
            ],
            options={
                'verbose_name': 'iMac',
                'verbose_name_plural': "iMac'и",
            },
        ),
        migrations.CreateModel(
            name='IMacOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Уникальный ID')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BaseSettings.colorproduct', verbose_name='Цвет')),
                ('imac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.imac', verbose_name='iMac')),
                ('images', models.ManyToManyField(related_name='all_images_imac_options', to='BaseSettings.imagesproduct', verbose_name='Изображение')),
                ('memory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BaseSettings.memoryproducts', verbose_name='Память')),
            ],
            options={
                'verbose_name': 'Параметры IMac',
                'verbose_name_plural': "Параметры IMac'ов",
            },
        ),
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название товара')),
                ('allColors', models.ManyToManyField(related_name='all_colors_phone', to='BaseSettings.colorproduct', verbose_name='Цвета товара')),
                ('allMemory', models.ManyToManyField(related_name='all_memory_phone', to='BaseSettings.memoryproducts', verbose_name='Память')),
                ('allSim', models.ManyToManyField(related_name='all_SIM_phone', to='BaseSettings.simproduct', verbose_name='Тип симкарты')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефоны',
            },
        ),
        migrations.CreateModel(
            name='PhonesOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Уникальный ID')),
                ('used', models.BooleanField(default=False, verbose_name='Подержанный')),
                ('discountedPrice', models.IntegerField(blank=True, null=True, verbose_name='Цена со скидкой')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BaseSettings.colorproduct', verbose_name='Цвет')),
                ('images', models.ManyToManyField(related_name='images_phone_options', to='BaseSettings.imagesproduct', verbose_name='Изображение')),
                ('memory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BaseSettings.memoryproducts', verbose_name='Память')),
                ('phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.phones', verbose_name='Устройство')),
                ('sim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BaseSettings.simproduct', verbose_name='Тип сим-карты')),
            ],
        ),
    ]
