# Generated by Django 5.0.6 on 2024-06-02 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_phones_manufacturer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessoriesoptions',
            options={'verbose_name': 'Вариант аксессуара', 'verbose_name_plural': 'Варианты аксессуаров'},
        ),
    ]
