# Generated by Django 5.0.6 on 2024-07-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseSettings', '0003_alter_manufacturer_options'),
        ('Core', '0005_alter_phonesoptions_options_phonesoptions_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonesoptions',
            name='memory',
        ),
        migrations.RemoveField(
            model_name='phonesoptions',
            name='sim',
        ),
        migrations.AddField(
            model_name='phonesoptions',
            name='allMemory',
            field=models.ManyToManyField(related_name='all_memory_phone_option', to='BaseSettings.memoryproducts', verbose_name='Память'),
        ),
        migrations.AddField(
            model_name='phonesoptions',
            name='allSim',
            field=models.ManyToManyField(related_name='all_SIM_phone_option', to='BaseSettings.simproduct', verbose_name='Тип симкарты'),
        ),
    ]
