# Generated by Django 5.0.6 on 2024-07-09 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseSettings', '0003_alter_manufacturer_options'),
        ('Core', '0006_remove_phonesoptions_memory_remove_phonesoptions_sim_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonesoptions',
            options={'verbose_name': 'Варианты телефона'},
        ),
        migrations.RemoveField(
            model_name='phonesoptions',
            name='allMemory',
        ),
        migrations.RemoveField(
            model_name='phonesoptions',
            name='allSim',
        ),
        migrations.RemoveField(
            model_name='phonesoptions',
            name='count',
        ),
        migrations.AddField(
            model_name='phonesoptions',
            name='memory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BaseSettings.memoryproducts', verbose_name='Память'),
        ),
        migrations.AddField(
            model_name='phonesoptions',
            name='sim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BaseSettings.simproduct', verbose_name='Тип сим-карты'),
        ),
    ]
