# Generated by Django 5.0.6 on 2024-07-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_alter_phonesoptions_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonesoptions',
            name='count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество: '),
        ),
    ]
