# Generated by Django 5.0.7 on 2024-07-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_phonesoptions_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonesoptions',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Название'),
        ),
    ]
