# Generated by Django 5.0.7 on 2024-07-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseSettings', '0003_alter_manufacturer_options'),
        ('Core', '0009_phonesoptions_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='allMemory',
            field=models.ManyToManyField(blank=True, null=True, to='BaseSettings.memoryproducts', verbose_name='Память'),
        ),
    ]
