# Generated by Django 5.0.7 on 2024-07-22 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_alter_accessories_allmemory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessories',
            name='images',
        ),
    ]
