# Generated by Django 5.0.7 on 2024-07-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0014_accessoriesoptions_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoriesoptions',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
