# Generated by Django 5.0.7 on 2024-07-22 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0015_accessoriesoptions_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonesoptions',
            options={'verbose_name': 'Вариант телефона', 'verbose_name_plural': 'Варианты телефонов'},
        ),
    ]
