# Generated by Django 5.0.7 on 2024-07-29 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseSettings', '0003_alter_manufacturer_options'),
        ('Core', '0016_alter_phonesoptions_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoversOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Уникальный ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Название')),
                ('discountedPrice', models.IntegerField(blank=True, null=True, verbose_name='Цена со скидкой')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BaseSettings.colorproduct', verbose_name='Цвет')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.covers', verbose_name='Устройство')),
                ('images', models.ManyToManyField(related_name='images_cover_options', to='BaseSettings.imagesproduct', verbose_name='Изображение')),
            ],
        ),
    ]
