# Generated by Django 5.0.7 on 2024-07-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0017_coversoptions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coversoptions',
            options={'verbose_name': 'Вариант чехла', 'verbose_name_plural': 'Варианты чехлов'},
        ),
        migrations.AddField(
            model_name='coversoptions',
            name='used',
            field=models.BooleanField(default=True, verbose_name='Подержанный'),
        ),
    ]
