# Generated by Django 5.0.7 on 2024-07-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0018_alter_coversoptions_options_coversoptions_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coversoptions',
            name='used',
            field=models.BooleanField(default=False, verbose_name='Подержанный'),
        ),
    ]
