# Generated by Django 5.0.7 on 2024-07-29 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0019_alter_coversoptions_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covers',
            old_name='color',
            new_name='allcolor',
        ),
    ]
