# Generated by Django 5.0.7 on 2024-07-29 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseSettings', '0003_alter_manufacturer_options'),
        ('Core', '0020_rename_color_covers_allcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BaseSettings.manufacturer', verbose_name='Производитель'),
        ),
    ]
