# Generated by Django 5.0.7 on 2024-07-29 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0021_accessories_manufacturer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covers',
            old_name='allcolor',
            new_name='allColor',
        ),
    ]
