# Generated by Django 5.0.7 on 2024-07-29 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0022_rename_allcolor_covers_allcolor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covers',
            old_name='allColor',
            new_name='allColors',
        ),
    ]
