# Generated by Django 5.0.7 on 2024-08-01 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseSettings', '0004_ram'),
        ('Core', '0023_rename_allcolor_covers_allcolors'),
    ]

    operations = [
        migrations.AddField(
            model_name='imacoptions',
            name='RAM',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BaseSettings.ram', verbose_name='Память'),
        ),
    ]
