# Generated by Django 5.0.7 on 2024-08-05 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseSettings', '0004_ram'),
        ('Core', '0024_imacoptions_ram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessoriesoptions',
            name='sim',
        ),
        migrations.AlterField(
            model_name='imacoptions',
            name='RAM',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BaseSettings.ram', verbose_name='Объединенная память'),
        ),
    ]
