# Generated by Django 5.0.7 on 2024-08-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0025_remove_accessoriesoptions_sim_alter_imacoptions_ram'),
    ]

    operations = [
        migrations.AddField(
            model_name='imacoptions',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Название'),
        ),
    ]
