# Generated by Django 5.0.6 on 2024-05-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название товара')),
                ('color', models.CharField(max_length=30, verbose_name='Цвет товара')),
                ('sim', models.CharField(blank=True, choices=[('SIM_SIM', 'SIM + SIM'), ('ESIM_SIM', 'ESIM + SIM'), ('ESIM_ONLY', 'ESIM ONLY')], max_length=20, null=True)),
            ],
        ),
    ]
