# Generated by Django 5.0.6 on 2024-05-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='product',
            name='memory',
            field=models.CharField(blank=True, choices=[('128Gb', '128Gb'), ('256Gb', '256Gb'), ('512Gb', '512Gb'), ('1024Gb', '1024Gb')], max_length=8, null=True, verbose_name='Память'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sim',
            field=models.CharField(blank=True, choices=[('SIM_SIM', 'SIM + SIM'), ('ESIM_SIM', 'ESIM + SIM'), ('ESIM_ONLY', 'ESIM ONLY')], max_length=20, null=True, verbose_name='СИМ КАРТА'),
        ),
    ]
