# Generated by Django 5.0.6 on 2024-05-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_alter_product_options_product_memory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название цвета')),
                ('codeColor', models.CharField(max_length=30, verbose_name='Код цвета HEX/RGB/RGBa')),
            ],
        ),
        migrations.CreateModel(
            name='ImagesProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название изображения')),
                ('photo', models.ImageField(upload_to='media/ProductImages/', verbose_name='Изображение')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.AlterField(
            model_name='product',
            name='memory',
            field=models.CharField(blank=True, choices=[('128Gb', '128Gb'), ('256Gb', '256Gb'), ('512Gb', '512Gb'), ('1024Gb', '1024Gb'), ('2048Gb', '2048Gb')], max_length=8, null=True, verbose_name='Память'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(to='Core.colorproduct'),
        ),
    ]
