# Generated by Django 5.0.6 on 2024-05-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_colorproduct_imagesproduct_remove_product_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(to='Core.imagesproduct'),
        ),
    ]
