# Generated by Django 5.0.6 on 2024-05-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_product_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colorproduct',
            options={'verbose_name': 'Цвет товара', 'verbose_name_plural': 'Цвет товаров'},
        ),
        migrations.AlterModelOptions(
            name='imagesproduct',
            options={'verbose_name': 'Изображение товара', 'verbose_name_plural': 'Изображения товаров'},
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(to='Core.colorproduct', verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(to='Core.imagesproduct', verbose_name='Изображение'),
        ),
    ]
