# Generated by Django 5.0.6 on 2024-05-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_alter_colorproduct_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unique_id',
            field=models.SlugField(default=2, editable=False, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
