# Generated by Django 5.0.6 on 2024-05-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_product_unique_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='NewDevices',
        ),
        migrations.AlterModelOptions(
            name='newdevices',
            options={'verbose_name': 'Новое устройство', 'verbose_name_plural': 'Новые устройства'},
        ),
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.SlugField(editable=False, max_length=255, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='Название товара')),
                ('memory', models.CharField(blank=True, choices=[('8Gb', '8Gb'), ('16Gb', '16Gb'), ('32Gb', '32Gb')], max_length=8, null=True, verbose_name='Память')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('color', models.ManyToManyField(to='Core.colorproduct', verbose_name='Цвет')),
                ('images', models.ManyToManyField(to='Core.imagesproduct', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Аксессуар',
                'verbose_name_plural': 'Аксессуары',
            },
        ),
        migrations.CreateModel(
            name='Covers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.SlugField(editable=False, max_length=255, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='Название товара')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('color', models.ManyToManyField(to='Core.colorproduct', verbose_name='Цвет')),
                ('images', models.ManyToManyField(to='Core.imagesproduct', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Чехол',
                'verbose_name_plural': 'Чехлы',
            },
        ),
        migrations.CreateModel(
            name='IMac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.SlugField(editable=False, max_length=255, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='Название товара')),
                ('memory', models.CharField(blank=True, choices=[('8Gb', '8Gb'), ('16Gb', '16Gb'), ('32Gb', '32Gb')], max_length=8, null=True, verbose_name='Память')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('color', models.ManyToManyField(to='Core.colorproduct', verbose_name='Цвет')),
                ('images', models.ManyToManyField(to='Core.imagesproduct', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'IMac',
                'verbose_name_plural': "IMac'и",
            },
        ),
        migrations.CreateModel(
            name='UsedDevices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.SlugField(editable=False, max_length=255, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='Название товара')),
                ('memory', models.CharField(blank=True, choices=[('128Gb', '128Gb'), ('256Gb', '256Gb'), ('512Gb', '512Gb'), ('1024Gb', '1024Gb'), ('2048Gb', '2048Gb')], max_length=8, null=True, verbose_name='Память')),
                ('sim', models.CharField(blank=True, choices=[('SIM_SIM', 'SIM + SIM'), ('ESIM_SIM', 'ESIM + SIM'), ('ESIM_ONLY', 'ESIM ONLY')], max_length=20, null=True, verbose_name='СИМ КАРТА')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('color', models.ManyToManyField(to='Core.colorproduct', verbose_name='Цвет')),
                ('images', models.ManyToManyField(to='Core.imagesproduct', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Б/У устройство',
                'verbose_name_plural': 'Б/У устройства',
            },
        ),
    ]
