# Generated by Django 5.0.6 on 2024-05-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_rename_product_newdevices_alter_newdevices_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesproduct',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название изображения'),
        ),
        migrations.AlterField(
            model_name='newdevices',
            name='color',
            field=models.ManyToManyField(to='Core.colorproduct', verbose_name='Цвет товара'),
        ),
    ]
