# Generated by Django 5.0.6 on 2024-05-30 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_alter_imagesproduct_name_alter_newdevices_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='newdevices',
            name='allColors',
            field=models.ManyToManyField(related_name='devices', to='Core.colorproduct', verbose_name='Все варианты цветов товара'),
        ),
        migrations.RemoveField(
            model_name='newdevices',
            name='color',
        ),
        migrations.AlterField(
            model_name='newdevices',
            name='images',
            field=models.ManyToManyField(related_name='devices', to='Core.imagesproduct', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='newdevices',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_devices', to='Core.colorproduct', verbose_name='Цвет товара'),
        ),
    ]
