# Generated by Django 5.0.6 on 2024-05-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_newdevices_allcolors_remove_newdevices_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newdevices',
            name='discountedPrice',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена со скидкой'),
        ),
    ]
