# Generated by Django 5.0.6 on 2024-07-09 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseSettings', '0002_manufacturer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
    ]
